### metaclean test/demo code
# 
# J.Draper 28 June 2018
#
# run metaclean functions on a sample phyloseq object generated by following
# the dada2 tutorial  https://benjjneb.github.io/dada2/tutorial.html
# (with fake DNA_Concentration values added to the sample_data table)
#


#load libraries
library(phyloseq); library(dplyr); library(metaclean)

#create a directory to store the output:
dir.create("./test/output", showWarnings = FALSE)

#load a  phyloseq object:
ps <- readRDS("./test/dada2_tutorial_physeq.rds")

#this is a silva taxonomy, so extend the plastid taxon levels
ps <- ExtendPlastidTax(ps)

#this is a dada2 dataset, so convert the sequences to seqID's
ret <- metaclean::ReplaceSeqIDs(ps, "./test/output/seqids.fa")
ps <- ret$physeq  #the new phyloseq object
otus <- ret$otu_map  #the Seq -> SeqID mapping df

#write the SeqID->Seq table as .csv for easier work later
write.csv(ret$otu_map, "./test/output/seqids.csv")

#save the renamed phyloseq object:
saveRDS(ret$physeq, "./test/phyloseq_dada2_renamed.rds")


#### create some biologist-friendly output tables
#get the metadata
metadata <- suppressWarnings( as.data.frame( sample_data(ps) ) )
#generate the tables
ret <- metaclean::CreateTables(ps, metadata, colnames(metadata), 
                               key="SampleID", otu_map=otus)
#write the tables
write.csv(ret$master, "./test/output/master_table.csv")
write.csv(ret$sum, "./test/output/summary_table.csv")
write.csv(ret$otu, "./test/output/otu_table.csv")
write.csv(ret$tax, "./test/output/tax_table.csv")



#### create relative abundance tables
#
ps <- metaclean::CreateRelabund(ps, filt=1e-5)

#look at the output
ps$orig  #the original count table
ps$r     #converted to per-sample relative abundance
ps$fr    #ps$r filtered to only seqs with mean abundance across all samples >1e-5



###### remove taxa found in the mock community
#
#get the metadata
metadata <- suppressWarnings( as.data.frame( sample_data(ps$orig) ) )

#pull out the names of the mock samples
mock_samples <- suppressWarnings( as.character( 
                                  filter(metadata, (When == "Mock"))$SampleID
                                  ))

#create a version with just the mocks
ps_mocks <- metaclean::SubsetSamples(ps$orig, mock_samples)
ps_mocks <- metaclean::CreateRelabund(ps_mocks, filt=1e-5)

#look at the taxa found in the mocks
mock_taxa <- phyloseq::taxa_names(ps_mocks$orig)
all_taxa <- phyloseq::taxa_names(ps$orig)

#create a version with the mocks removed
ps_nomocks <- metaclean::RemoveTaxa(ps$orig, mock_taxa, prune=TRUE)
ps_nomocks <- metaclean::CreateRelabund(ps_nomocks, filt=1e-5)
ps_nomocks

#create a version with all samples, but only taxa found in the mock samples
ps_mocktaxa <- phyloseq::prune_taxa(mock_taxa, ps$orig) #prune_taxa() specifies what taxa to keep
ps_mocktaxa <- metaclean::CreateRelabund(ps_mocktaxa, filt=1e-5)
ps_mocktaxa

#check the result (note: may need to use nrow() here)
a <- ncol(phyloseq::otu_table(ps$r))
b <- ncol(phyloseq::otu_table(ps_nomocks$r))
print("Result of kit-mock filtering: ")
sprintf("original otus: %s    after correction: %s     difference: %s", a,b, b-a)
length(mock_taxa)



##### Remove the Jervis-Bardy predicted contaminant taxa
#

#calculate jb correlation
JB_corr <- metaclean::CalcSpearmanMatrix(phyloseq::otu_table(ps$r),
                                         phyloseq::sample_data(ps$r)$DNA_Concentration)

#get list of the OTUs to remove
jb_taxa <- rownames(JB_corr$negSigMatrix)
sprintf("The following %s OTUs will be removed:",length(jb_taxa))
jb_taxa

#create a version with the jb taxa removed
ps_nojb <- metaclean::RemoveTaxa(ps$orig, jb_taxa, prune=TRUE)
ps_nojb <- metaclean::CreateRelabund(ps_nojb, filt=1e-5)

#check the result  (note: may need to use nrow() here)
a <- ncol(phyloseq::otu_table(ps$r))
b <- ncol(phyloseq::otu_table(ps_nojb$r))
print("Result of Jervis-Bardy filtering: ")
sprintf("original otus: %s    after correction: %s     difference: %s", a,b, b-a)
#length(jb_taxa)

#create a version with just the bad taxa
ps_jbtaxa <- phyloseq::prune_taxa(jb_taxa, ps$orig) #prune_taxa() specifies what to keep
ps_jbtaxa <- metaclean::CreateRelabund(ps_jbtaxa, filt=1e-5)



##### Remove the mock AND jervis-bardy taxa
#

#prepare the list of contaminant taxa
contam_taxa <- unique(c(mock_taxa, jb_taxa))
contam_taxa

#create a version with the contaminant taxa removed
ps_nocontam <- metaclean::RemoveTaxa(ps$orig, contam_taxa)
ps_nocontam <- metaclean::CreateRelabund(ps_nocontam, filt=1e-5)

#create a version with just the contaminant taxa
ps_contamtaxa <- phyloseq::prune_taxa(contam_taxa, ps$orig) #prune_taxa() specifies what to keep
ps_contamtaxa <- metaclean::CreateRelabund(ps_contamtaxa, filt=1e-5)


#check the result  (note: may need to use nrow() here)
a <- ncol(phyloseq::otu_table(ps$orig))
b <- ncol(phyloseq::otu_table(ps_nocontam$orig))
print("Result of JB & kit-mock filtering: ")
sprintf("original otus: %s    after correction: %s     difference: %s", a,b, b-a)
#length(contam_taxa)



